name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArchiFlowDraft-debug
          path: android/app/build/outputs/apk/debug/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - name: Decode keystore (optional)
        working-directory: android
        env:
          SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$SIGNING_KEYSTORE_BASE64" ]; then
            echo "$SIGNING_KEYSTORE_BASE64" | base64 -d > keystore.jks
          fi
      - name: Build Release AAB
        working-directory: android
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          ./gradlew bundleRelease \
            -PstoreFile=keystore.jks \
            -PstorePassword=$SIGNING_STORE_PASSWORD \
            -PkeyAlias=$SIGNING_KEY_ALIAS \
            -PkeyPassword=$SIGNING_KEY_PASSWORD || ./gradlew bundleRelease
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            android/app/build/outputs/bundle/release/*.aab
