name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK 34
        run: |
          yes | sdkmanager --licenses
          sdkmanager "cmdline-tools;latest" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Debug APK (verbose)
        working-directory: android
        env:
          GRADLE_OPTS: >-
            -Dorg.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g
            -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
            -Dorg.gradle.configuration-cache=false
            -Dorg.gradle.internal.http.socketTimeout=180000
            -Dorg.gradle.internal.http.connectionTimeout=180000
        run: |
          ./gradlew --no-daemon --stacktrace --info clean :app:assembleDebug

      - name: Upload debug APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ArchiFlowDraft-debug
          path: android/app/build/outputs/apk/debug/*.apk
