name: Integración Continua de Android
​on:
push:
branches: [ main ]
pull_request:
workflow_dispatch:
​jobs:
build:
runs-on: ubuntu-latest
timeout-minutes: 60

    steps: # <-- Corregido: Ahora está correctamente indentado bajo 'build'
  - name: Checkout del Repositorio
    uses: actions/checkout@v4

  - name: Configurar JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17
      
  - name: Cache de Gradle
    uses: actions/cache@v4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: ${{ runner.os }}-gradle-${{ hashFiles('android/build.gradle', 'android/settings.gradle') }}
      restore-keys: |
        ${{ runner.os }}-gradle-

  - name: Instalar SDK 34, Herramientas de Plataforma y aceptar licencias
    uses: android-actions/setup-android@v3
    with:
      api-level: 34
      build-tools: 34.0.0

  - name: Dar permisos de ejecución a gradlew
    run: chmod +x android/gradlew

  - name: Construir APK de Depuración (modo detallado)
    working-directory: android
    env:
      GRADLE_OPTS: >-
        -Dorg.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=-Xmx2g
        -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
        -Dorg.gradle.internal.http.socketTimeout=180000
        -Dorg.gradle.internal.http.connectionTimeout=180000
    run: |
      ./gradlew --no-daemon --stacktrace --info clean :app:assembleDebug

  - name: Subir artefacto APK de depuración
    if: success()
    uses: actions/upload-artifact@v4
    with:
      name: ArchiFlowDraft-debug
      path: android/app/build/outputs/apk/debug/*.apk
